project:
  type: book
  output-dir: docs

book:
  output-file: "lecs"
  title: "Статистика и анализ данных в R: методы и приложения в психологии и социальных науках"
  subtitle: "Конспекты лекций"
  author: "А. Н. Ангельгардт"
  date: today
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - part: part-r.qmd
      chapters:
        - intro.qmd
        - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    include-in-header: 
      text: |
        \usepackage[english,russian]{babel}
        \addtokomafont{disposition}{\rmfamily}
        \usepackage{amsmath,amsfonts,amssymb,amsthm,mathtools}
    mainfont: "Times New Roman"



